# Generated by Django 4.2.7 on 2026-01-29 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khu vực giao hàng')),
                ('area_description', models.TextField(verbose_name='Mô tả khu vực')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Phí giao hàng')),
                ('delivery_time', models.CharField(max_length=50, verbose_name='Thời gian giao hàng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Khu vực giao hàng',
                'verbose_name_plural': 'Khu vực giao hàng',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên trang trại')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('organic_certified', models.BooleanField(default=False, verbose_name='Chứng nhận hữu cơ')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Số chứng nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trang trại',
                'verbose_name_plural': 'Trang trại',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('delivery_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('delivery_latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ giao hàng')),
                ('delivery_longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ giao hàng')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền hàng')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Phí giao hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_store.customer', verbose_name='Khách hàng')),
                ('delivery_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_store.deliveryzone', verbose_name='Khu vực giao hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá (VNĐ)')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Đơn vị')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh chính')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('nutritional_info', models.TextField(blank=True, verbose_name='Thông tin dinh dưỡng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_store.category', verbose_name='Danh mục')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_store.farm', verbose_name='Trang trại')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn hàng',
                'verbose_name_plural': 'Sản phẩm trong đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_store.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong giỏ hàng',
                'verbose_name_plural': 'Sản phẩm trong giỏ hàng',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
