# Generated by Django 4.2.7 on 2026-01-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrangTrai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('vi_do', models.FloatField()),
                ('kinh_do', models.FloatField()),
                ('mo_ta', models.TextField(blank=True)),
            ],
        ),
    ]
