# Generated by Django 6.0.1 on 2026-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0002_order_assigned_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.FloatField(blank=True, help_text='Khoảng cách đường bộ thực tế từ farm đến khách hàng', null=True, verbose_name='Khoảng cách giao hàng (km)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_duration_min',
            field=models.FloatField(blank=True, help_text='Thời gian di chuyển ước tính', null=True, verbose_name='Thời gian giao hàng (phút)'),
        ),
    ]
