# Generated by Django 6.0.1 on 2026-03-30 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0005_alter_cart_options_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Người liên hệ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('tax_code', models.CharField(blank=True, max_length=50, verbose_name='Mã số thuế')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Ngày kiểm kê')),
                ('total_products', models.IntegerField(default=0, verbose_name='Tổng số sản phẩm')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Tổng số lượng')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng giá trị')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reports', to='food_store.farm', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Báo cáo kiểm kê',
                'verbose_name_plural': 'Báo cáo kiểm kê',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Sắp hết hàng'), ('out_of_stock', 'Hết hàng'), ('overstock', 'Tồn kho quá nhiều'), ('expiring_soon', 'Sắp hết hạn')], max_length=20, verbose_name='Loại cảnh báo')),
                ('threshold', models.IntegerField(help_text='Số lượng tồn kho để kích hoạt cảnh báo', verbose_name='Ngưỡng cảnh báo')),
                ('current_stock', models.IntegerField(verbose_name='Tồn kho hiện tại')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='food_store.farm', verbose_name='Cửa hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='food_store.product', verbose_name='Sản phẩm')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Cảnh báo tồn kho',
                'verbose_name_plural': 'Cảnh báo tồn kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho'), ('adjustment', 'Điều chỉnh'), ('return', 'Trả hàng'), ('damaged', 'Hư hỏng')], max_length=20, verbose_name='Loại giao dịch')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Đơn giá')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tổng tiền')),
                ('stock_before', models.IntegerField(verbose_name='Tồn kho trước')),
                ('stock_after', models.IntegerField(verbose_name='Tồn kho sau')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='Số chứng từ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='food_store.farm', verbose_name='Cửa hàng')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='food_store.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='food_store.product', verbose_name='Sản phẩm')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_store.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Giao dịch kho',
                'verbose_name_plural': 'Giao dịch kho',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='food_store__created_318c1b_idx'), models.Index(fields=['product', '-created_at'], name='food_store__product_bee5b6_idx'), models.Index(fields=['farm', '-created_at'], name='food_store__farm_id_057a7e_idx')],
            },
        ),
    ]
