# Generated by Django 6.0.1 on 2026-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0006_supplier_inventoryreport_stockalert_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo'), ('zalopay', 'ZaloPay')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
