# Generated by Django 6.0.1 on 2026-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mã tham chiếu thanh toán'),
        ),
    ]
