# Generated by Django 6.0.1 on 2026-03-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0008_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Số tiền thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
    ]
