# Generated by Django 6.0.1 on 2026-03-31 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0009_order_payment_amount_order_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='food_store.farm', verbose_name='Cửa hàng phụ trách'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_store.customer', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Khoảng cách giao hàng (km)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_duration_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Thời gian giao hàng (phút)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Phí giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_store.deliveryzone', verbose_name='Khu vực giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_store.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_store.farm', verbose_name='Cửa hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Còn hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=models.TextField(blank=True, verbose_name='Thông tin dinh dưỡng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=20, verbose_name='Đơn vị'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
