# Generated by Django 4.2.7 on 2026-04-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0011_shipper_order_shipper_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
