# Generated by Django 4.2.7 on 2026-04-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_shipper',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipper_assigned_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipper_picked_at',
        ),
        migrations.DeleteModel(
            name='Shipper',
        ),
    ]
