# Generated by Django 4.2.7 on 2026-04-05 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_store', '0013_remove_order_assigned_shipper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/', verbose_name='Ảnh chứng minh giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nhận đơn'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú của shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_picked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian lấy hàng'),
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('vehicle_number', models.CharField(max_length=50, verbose_name='Biển số xe')),
                ('status', models.CharField(choices=[('available', 'Sẵn sàng'), ('busy', 'Đang giao hàng'), ('offline', 'Đang nghỉ')], default='offline', max_length=20, verbose_name='Trạng thái')),
                ('total_deliveries', models.IntegerField(default=0, verbose_name='Tổng số đơn đã giao')),
                ('today_deliveries', models.IntegerField(default=0, verbose_name='Số đơn hôm nay')),
                ('cod_holding', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền COD đang giữ')),
                ('today_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Thu nhập hôm nay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='food_store.shipper', verbose_name='Shipper phụ trách'),
        ),
    ]
