# Generated by Django 6.0.1 on 2026-04-14 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0014_order_proof_image_order_shipper_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='assigned_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shippers', to='food_store.farm', verbose_name='Chi nhánh phụ trách'),
        ),
        migrations.CreateModel(
            name='StoreAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('can_manage_products', models.BooleanField(default=True, verbose_name='Quản lý sản phẩm')),
                ('can_manage_orders', models.BooleanField(default=True, verbose_name='Quản lý đơn hàng')),
                ('can_manage_inventory', models.BooleanField(default=True, verbose_name='Quản lý kho')),
                ('can_manage_shippers', models.BooleanField(default=True, verbose_name='Quản lý shipper')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Xem báo cáo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_admins', to='food_store.farm', verbose_name='Chi nhánh quản lý')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Quản lý chi nhánh',
                'verbose_name_plural': 'Quản lý chi nhánh',
            },
        ),
    ]
