# Generated by Django 6.0.1 on 2026-04-15 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_store', '0015_shipper_assigned_farm_storeadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Mã OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('expires_at', models.DateTimeField(verbose_name='Thời gian hết hạn')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác thực')),
                ('attempts', models.IntegerField(default=0, verbose_name='Số lần thử')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password (hashed)')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Họ')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Tên')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
            ],
            options={
                'verbose_name': 'Xác thực Email',
                'verbose_name_plural': 'Xác thực Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Mã OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('expires_at', models.DateTimeField(verbose_name='Thời gian hết hạn')),
                ('is_used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
                ('attempts', models.IntegerField(default=0, verbose_name='Số lần thử')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reset Password',
                'verbose_name_plural': 'Reset Password',
                'ordering': ['-created_at'],
            },
        ),
    ]
